
    <footer>
        <div class="fixed-bottom todo-footer bg-dark"> 
            <div class="todo-copy">
                Copyright &copy; <?= date('Y') ?> <span class="author">Fabiano Basso</span>  
            </div>
            <div class="todo-version">
                <span class="version">@Versão 1.0</span> 
            </div>
        </div>
    </footer>

    <script>
            $(document).ready(() =>{
                $('#dashboard').on('click', e =>{
                    $(location).attr('href','app.php?dashboard')
                })

                $('#newTask').on('click', e =>{
                    $(location).attr('href','app.php?newTask')
                })

                $('#pedingTask').on('click', e =>{
                    $(location).attr('href','app.php?pedingTask')
                })

                $('#completeTask').on('click', e =>{
                    $(location).attr('href','app.php?completeTask')
                })
            })
    </script>

    <!-- Script Functions custom app todo list -->
    <script src="assets/js/functions.js"></script>
    <!-- Script BootStrap -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>