<!DOCTYPE html>
<html lang="pt-br" id="teste">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App Lista de Tarefas</title>
    <link rel="shortcut icon" href="assets/img/favicon.png" type="image/x-icon">
    <!-- Css customizado -->
    <link rel="stylesheet" href="assets/css/style.css">
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- font awesome 5.15-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <!-- Script jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</head>

<body>

    <nav class="navbar navbar-light bg-dark">
            <div class="container">
                <a href="#" class="navbar-brand">
                    <img src="assets/img/logo.svg" width="60" height="60" class="d-inline-block align-middle" alt="App Lista de Tarefas">
                    <span class="logo">App Lista de Tarefas</span>
                </a>
                <div class="logout">
                    <a href="logout.php" class="icon-logout"><i class="fas fa-sign-out-alt"></i></a>
                </div>
            </div>
    </nav>

