<div class="container mt-5">
    <div class="dashboard-content">
        <div class="col-md-3 menu">
            <ul class="list-group">
                <li class="list-group-item azul-claro " id="item-1"><a href="#" id="dashboard">Dashboard</a></li>
                <li class="list-group-item verde" id="item-2"><a href="#" id="newTask">Nova tarefa</a></li>
                <li class="list-group-item vermelho active" id="item-3"><a href="#" id="pedingTask">Tarefas pendente</a></li>
                <li class="list-group-item azul" id="item-4"><a href="#" id="completeTask">Tarefas concluída</a></li>
            </ul>
        </div>
        <div class="col-md-9">
            <div class="container pagina">
                        
                <div class="col">
                    <h4>Tarefas Pendente</h4>
                    <hr>

                    <div class="row mb-3 d-flex align-items-center tarefa">
                        <!-- Inicio tarefa -->
                        <div class="col-sm-9">Lavar Carro</div>
                            <div class="col-sm-3 mt-2 d-flex justify-content-between">
                                <i class="fas fa-trash-alt fa-lg text-danger"></i>
                                <i class="fas fa-edit fa-lg text-info"></i>
                                <i class="fas fa-check-square fa-lg text-success"></i>
                            </div>
                        </div>
                        <!-- Fim tarefa -->

                        <!-- Inicio tarefa -->
                        <div class="col-sm-9">Lavar Carro</div>
                            <div class="col-sm-3 mt-2 d-flex justify-content-between">
                                <i class="fas fa-trash-alt fa-lg text-danger"></i>
                                <i class="fas fa-edit fa-lg text-info"></i>
                                <i class="fas fa-check-square fa-lg text-success"></i>
                            </div>
                        </div>
                        <!-- Fim tarefa -->

                    </div>
                </div>

            </div>            
        </div>
    </div>
</div>